server:
  port: 8084

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
