input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "[@metadata][target_index]" => "auction-logs-%{+YYYY.MM.dd}"
    }
  }

  if [traceId] {
    mutate {
      add_field => { "traceId" => "%{traceId}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
}
